apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: ""   # 🔥 IMPORTANT
  volumeName: redis-pv   # 🔥 FORCE bind
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi