apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: raj-pvc

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp3-storage

  resources:
    requests:
      storage: 4Gi