replicaCount: 2

image:
  repository: rajspy/movie-api
  tag: 9bfbd78c42092cb425b17359effe83eca5d6b87d
  pullPolicy: IfNotPresent


service:
  type: NodePort
  port: 8000

ingress:
  host: movie.local

redis:
  host: redis
  port: 6379

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
