replicaCount: 2

image:
  repository: rajspy/movie-api
  tag: d5ce29d478f082bed6398e26ebed110e11ab16b9
  pullPolicy: IfNotPresent


service:
  type: NodePort
  port: 8000

ingress:
  host: movie.local

redis:
  host: redis
  port: 6379

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
