apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: movie-api
  template:
    metadata:
      labels:
        app: movie-api
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: movie-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
