name: Push to ECR

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::257394469486:role/github-oidc-role
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t movie-api .

      - name: Tag image
        run: docker tag movie-api:latest 257394469486.dkr.ecr.ap-south-1.amazonaws.com/movie-api:latest

      - name: Push image
        run: docker push 257394469486.dkr.ecr.ap-south-1.amazonaws.com/movie-api:latest